import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import demo from './__fixtures__/demo-workspace.json' with { type: 'json' };
import golden from './__fixtures__/legacy-parity.json' with { type: 'json' };
import { anchoredVariant, freeFormVariant } from './__fixtures__/parity-variants.js';
import { importLegacy } from './legacy.js';
import { emptyWorkspace } from './schema.js';
import { ingestKitMarkdown } from './ingest-kit.js';

/**
 * index.html's own `ingestKitMarkdown()` on the demo, captured headless with the clock at
 * `golden.now` by scripts/capture-legacy-parity.mjs.
 */
const LEGACY_KIT = readFileSync(
  fileURLToPath(new URL('./__fixtures__/legacy-ingest-kit.md', import.meta.url)),
  'utf8',
  // The kit is written with \n only; a checkout with autocrlf would otherwise fail on the file, not
  // on the port.
).replace(/\r\n/g, '\n');
const NOW = new Date(golden.now);

async function sha256(text: string): Promise<string> {
  const digest = await globalThis.crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

describe('the LLM Ingest Kit', () => {
  const { workspace } = importLegacy(demo);

  it('is byte for byte the kit index.html writes for the demo', () => {
    expect(ingestKitMarkdown(workspace, { now: NOW })).toBe(LEGACY_KIT);
  });

  it('matches index.html on workspaces that reach the rest of its vocabulary', async () => {
    // Anchored and Chart-Linked flows, a free-form chart, a roster past every cap of the crib sheet.
    for (const [name, raw] of [
      ['anchored', anchoredVariant(demo)],
      ['freeform', freeFormVariant(demo)],
    ] as const) {
      const kit = ingestKitMarkdown(importLegacy(raw).workspace, { now: NOW });
      expect(await sha256(kit), name).toBe(golden.cases[name].kit);
    }
  });

  it('dates itself from the clock it is given, in UTC as the legacy does', () => {
    const kit = ingestKitMarkdown(workspace, { now: new Date('2027-01-01T03:00:00+09:00') });
    expect(kit).toContain('Generated by ASIC RACI Tool ver 0.39 alpha on 2026-12-31.');
  });

  it('lists the workspace it was made from', () => {
    const kit = ingestKitMarkdown(workspace, { now: NOW });
    expect(kit).toContain('| `mission` | Mission Mgmt Dir. | MMD | `mission` |');
    expect(kit).toContain('| `hq` | Director / HQ | HQ | — |');
    expect(kit).toContain(
      '- `c_53jst3no` · "ASIC RACI Tool Demo" · raci · org chart · 11 top-tier row(s)',
    );
    expect(kit).toContain(
      '- `b_080aooen` · "Cyber Incident Response (Tabletop)" · raci · free · 6 step(s) · 1 nested flow(s) · 1 group(s) · standalone',
    );
    expect(kit).toContain('- `a_triage` · "Triage Report" · document');
  });

  it('says so when there is nothing to list', () => {
    const kit = ingestKitMarkdown(emptyWorkspace(), { now: NOW });
    expect(kit).toContain('- **ocio** · "DIRECTORATE A"\n    (no divisions yet)');
    expect(kit).toContain('### Business cases already in the workspace\n\n- (none)');
    expect(kit).toContain('- (none — name new ones freely)');
  });

  it('ends in a worked example this app can actually load', () => {
    // The kit tells a model to mirror the example; an example the importer rejected would teach it
    // to write files nobody can open.
    const kit = ingestKitMarkdown(workspace, { now: NOW });
    const json = /```json\n([\s\S]*?)\n```/.exec(kit)![1]!;
    const { workspace: example, report } = importLegacy(JSON.parse(json));
    expect(report.charts).toBe(2);
    expect(report.flows).toBe(1);
    expect(Object.values(example.flows)[0]!.anchor).toEqual({
      chartId: 'c_org',
      nodeId: 'n_task1',
    });
  });
});
